project:
  type: website

website:
  title: "LC-MS era"
  favicon: img/favicon.png
  description: "Blog page for LCMSera"
  
  navbar:
    pinned: true
    logo: /img/logo.png
    
    left:
      - text: "Courses"
        href: courses/index.qmd
    
    right:
      - text: Blog
        href: blog.qmd
      - icon: facebook
        href: https://facebook.com/lcmsera
      - icon: youtube
        href: https://youtube.com/@lcmsera
        
format:
  html:
    theme: slate
    css: styles.css

editor: visual

